[package]
name = "exchain-commons"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
uuid = { version = "1", features = ["v4"] }
